baseURL: "https://kreedzt.github.io/blog/"
title: "Kreedzt's blog"
languageCode: "zh-cn"
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
disqusShortname: "kreedzts-blog"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Kreedzt's blog"
    description: "Kreedzt's blog"
    keywords: ["Blog", "Portfolio", "PaperMod"]
    author: "Kreedzt"
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-01-02"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

socialIcons:
    #- name: twitter
    #  url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/Kreedzt"

analytics:
    #google:
    #  SiteVerificationTag: "XYZabc"
    #bing:
    #  SiteVerificationTag: "XYZabc"
    #yandex:
    #  SiteVerificationTag: "XYZabc"


cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

outputs:
    home:
        - HTML
        - RSS
        - JSON

fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archive
      url: archives
      weight: 5

    - name: Search
      url: search/
      weight: 10

    - name: Tags
      url: tags/
      weight: 10

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    style: monokai
